// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwefayfymegrdhuzoxth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3ZWZheWZ5bWVncmRodXpveHRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NDg5MDMsImV4cCI6MjA3MTUyNDkwM30.-hYqSK2CqyUXIHyEp07HCoNNON0XbLRLha_pOgA7lEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});